services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: medilabo_patient
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootroot"  ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - medilabo-net

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - medilabo-net

  patient-service:
    build: ./patient-service
    container_name: patient-service
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - medilabo-net

  note-service:
    build: ./note-service
    container_name: note-service
    ports:
      - "8083:8083"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/medilabo_note
    networks:
      - medilabo-net

  assessment-service:
    build: ./assessment-service
    container_name: assessment-service
    ports:
      - "8084:8084"
    networks:
      - medilabo-net

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - patient-service
      - note-service
      - assessment-service
    networks:
      - medilabo-net

  front-service:
    build: ./front-service
    container_name: front-service
    ports:
      - "8082:8082"
    depends_on:
      - gateway
    networks:
      - medilabo-net

networks:
  medilabo-net: